#!/bin/bash

# Managing EnergyLensPlus processes

# Change to the repository directory
ELENSHOME=`printenv ELENSERVER`
cd $ELENSHOME

#Take a backup of the existing log file
default_logfile="$ELENSHOME/logs/django.log"
main_logfile="$ELENSHOME/logs/energylens.log"
gcm_logfile="$ELENSHOME/logs/gcmserver.log"
worker_logfile="$ELENSHOME/logs/energylens-worker.log"
meterdata_logfile="$ELENSHOME/logs/meter_data.log"


#Get the command option
arg=$1

if [ "$arg" = 'start' ]; then

	echo "Starting EnergyLensPlus Server..."

	touch "$ELENSHOME/energylensplus/wsgi.py"

	# Start GCM Server
	python manage.py opengcmserver &
	sleep 5
	# python manage.py rungcmserver &

	# Start Celery
	sudo /etc/init.d/celeryd start
	# sleep 1
	sudo /etc/init.d/celerybeat start

	# Start Django-Apache Server
	sudo service apache2 start
		
	# Start Meter data collection service
	# python manage.py getmeterdata &
	
elif [ "$arg" = 'stop' ]; then
	echo "Stopping EnergyLensPlus Server.."

	# Stop Django Commands
	kill -9 `ps aux | grep "python manage.py" | grep -v grep | awk '{print $2}'`

	# Stop Django-Apache Server
	sudo service apache2 stop

	# Stop celery
	sudo /etc/init.d/celerybeat stop
	sudo /etc/init.d/celeryd stop

	# Managing log files
    cd "$ELENSHOME/logs/"
    no_of_log_files=$(ls -1 *.log | wc -l)
    if [ $no_of_log_files = 7 ]; then
	   cp $default_logfile "$ELENSHOME/logs/old_logs/django"_`date +%F_%T`".log"
	   cp $main_logfile "$ELENSHOME/logs/old_logs/energylens"_`date +%F_%T`".log"
	   cp $gcm_logfile "$ELENSHOME/logs/old_logs/gcmserver"_`date +%F_%T`".log"
	   cp $worker_logfile "$ELENSHOME/logs/old_logs/energylens-worker"_`date +%F_%T`".log"
	   cp $meterdata_logfile "$ELENSHOME/logs/old_logs/meter_data"_`date +%F_%T`".log"
	   
	   cat /dev/null > $default_logfile
	   cat /dev/null > $main_logfile
	   cat /dev/null > $gcm_logfile
	   cat /dev/null > $worker_logfile
	   cat /dev/null > $meterdata_logfile
	fi
    cd $ELENSHOME
	

elif [ "$arg" = 'restart' ]; then
	echo "Restarting EnergyLensPlus Server.."
	
	# Stop Django commands
	kill -9 `ps aux | grep "python manage.py" | grep -v grep | awk '{print $2}'`

	# Django Server
	touch "$ELENSHOME/energylensplus/wsgi.py"

	# Start GCM Server
	python manage.py opengcmserver &
	sleep 5
	# python manage.py rungcmserver &

	# Restart Celery
	sudo /etc/init.d/celerybeat restart
	sudo /etc/init.d/celeryd restart

	# Start Meter data collection service
	# python manage.py getmeterdata &

	
elif [ "$arg" = 'update' ]; then
	echo "Updating EnergyLensPlus Server..."
	git pull	

elif [ "$arg" = 'status' ]; then
	echo "Celery Status:"
	sudo /etc/init.d/celerybeat status
	sudo /etc/init.d/celeryd status
	# if [ -f $serverPIDFile ]; then
	# 	echo "EnergyLensPlus Server has already started"
	# else
	# 	echo "EnergyLensPlus Server has not been started. To start, type:"
	# 	echo -e '\t energylens start <ip_addr:port_no>'
	# fi
else
	echo 'Wrong command. Please type in this format-> source sensoract <start|stop|update|restart|status>'
fi