#!/bin/bash

# Managing EnergyLensPlus processes

# TODO: Add process specific start/stop commands

# Change to the repository directory
HOME=`printenv ELENSERVER`
cd $HOME

#Take a backup of the existing log file
default_logfile=${HOME}"logs/django.log"
main_logfile=${HOME}"logs/energylens.log"
gcm_logfile=${HOME}"logs/gcmserver.log"
celery_logfile=${HOME}"logs/celery.log"
meterdata_logfile=${HOME}"logs/meter_data.log"


#Get the command option
arg=$1
ip=$2

if [ "$arg" = 'start' ]; then

   if [ $# -ne 2 ]
   # "$#" is number of parameters- here we test
   # whether it is not equal to two
   then
   echo "Command Error: No IP Address entered"
   echo "Usage: energylens start <ip_addr>"	# not two parameters
   # so print message
   exit 2             		# and fail ($0 is name of command).
   fi

    # Managing log files
    cd $HOME"logs/"
    no_of_log_files=$(ls -1 *.log | wc -l)
    if [ $no_of_log_files = 5 ]; then
	   cp $default_logfile ${HOME}"logs/old_logs/django"_`date +%F_%T`".log"
	   cp $main_logfile ${HOME}"logs/old_logs/energylens"_`date +%F_%T`".log"
	   cp $gcm_logfile ${HOME}"logs/old_logs/gcmserver"_`date +%F_%T`".log"
	   cp $celery_logfile ${HOME}"logs/old_logs/celery"_`date +%F_%T`".log"
	   cp $meterdata_logfile ${HOME}"logs/old_logs/meter_data"_`date +%F_%T`".log"
	   
	   cat /dev/null > $default_logfile
	   cat /dev/null > $main_logfile
	   cat /dev/null > $gcm_logfile
	   cat /dev/null > $celery_logfile
	   cat /dev/null > $meterdata_logfile
	fi
    cd $HOME

	echo "Starting EnergyLensPlus Server..."

	# Start GCM Server
	python manage.py opengcmserver &
	sleep 5
	python manage.py rungcmserver &

	# Start Celery
	celery -A energylensplus worker -l info -B  &
	
	# Start Django Server
	python manage.py runserver $ip &
	
	# Start Meter data collection service
	python manage.py getmeterdata &
	
elif [ "$arg" = 'stop' ]; then
	echo "Stopping EnergyLensPlus Server.."

	# Stop Django Commands
	kill -9 `ps aux | grep "python manage.py" | grep -v grep | awk '{print $2}'`

	# Stop celery
	kill -9 `ps aux | grep "celery" | grep -v grep | awk '{print $2}'`
	

elif [ "$arg" = 'restart' ]; then
	echo "Restarting EnergyLensPlus Server.."
	
elif [ "$arg" = 'update' ]; then
	echo "Updating EnergyLensPlus Server..."
	git pull	

elif [ "$arg" = 'status' ]; then
	pwd
	# if [ -f $brokerServerFile ]; then
	# 	echo "EnergyLensPlus Server has already started"
	# else
	# 	echo "EnergyLensPlus Server has not been started. To start, type:"
	# 	echo -e '\t source sensoract start'
	# fi
else
	echo 'Wrong command. Please type in this format-> source sensoract <start|stop|update|restart|status>'
fi